# 1. Importando Bibliotecas
Primeiramente, vamos importar as bibliotecas necessárias para nossa análise.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


# 2. Carregando o Conjunto de Dados
Usaremos o conjunto de dados "Wine" disponível no scikit-learn, que contém informações químicas de diferentes tipos de vinho.

In [ ]:
wine = datasets.load_wine()
X = wine.data
y = wine.target


# 3. Análise Exploratória de Dados
Vamos dar uma olhada nas primeiras linhas do conjunto de dados e entender suas características.

In [ ]:
df = pd.DataFrame(X, columns=wine.feature_names)
df['target'] = y
df.head()


,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0


# 4. Pré-processamento de Dados
Dividimos os dados em conjuntos de treinamento e teste.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)


Normalizamos os dados para melhorar o desempenho de alguns algoritmos.



In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# 5. Modelos de Aprendizado Supervisionado
5.1. K-Nearest Neighbors (KNN)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)


In [ ]:
y_pred_knn

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 2, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 0, 1, 0, 0, 1, 2, 0, 0, 0, 2, 2, 1, 2, 0, 1, 1, 1,
       2, 0, 1, 1, 2, 0, 1, 0, 0, 2])

5.2. Regressão Logística


In [ ]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)
y_pred_logreg = logreg.predict(X_test)


5.3. Árvores de Decisão


In [ ]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


5.4. Random Forest


In [ ]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train, y_train)
y_pred_forest = forest.predict(X_test)


5.5. Support Vector Machine (SVM)


In [ ]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)


# 6. Avaliação dos Modelos
Criamos uma função para avaliar os modelos de forma consistente.

In [ ]:
def avaliar_modelo(y_test, y_pred, nome_modelo):
    print(f"Resultados para {nome_modelo}:")
    print("Acurácia:", accuracy_score(y_test, y_pred))
    print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred))
    print("Relatório de Classificação:\n", classification_report(y_test, y_pred))
    print("-" * 60)


Avaliação de cada modelo:



In [ ]:
avaliar_modelo(y_test, y_pred_knn, "K-Nearest Neighbors")
avaliar_modelo(y_test, y_pred_logreg, "Regressão Logística")
avaliar_modelo(y_test, y_pred_tree, "Árvore de Decisão")
avaliar_modelo(y_test, y_pred_forest, "Random Forest")
avaliar_modelo(y_test, y_pred_svm, "Support Vector Machine")


Resultados para K-Nearest Neighbors:
Acurácia: 0.9629629629629629
Matriz de Confusão:
 [[19  0  0]
 [ 1 19  1]
 [ 0  0 14]]
Relatório de Classificação:
               precision    recall  f1-score   support

           0       0.95      1.00      0.97        19
           1       1.00      0.90      0.95        21
           2       0.93      1.00      0.97        14

    accuracy                           0.96        54
   macro avg       0.96      0.97      0.96        54
weighted avg       0.97      0.96      0.96        54

------------------------------------------------------------
Resultados para Regressão Logística:
Acurácia: 0.9814814814814815
Matriz de Confusão:
 [[19  0  0]
 [ 0 20  1]
 [ 0  0 14]]
Relatório de Classificação:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.95      0.98        21
           2       0.93      1.00      0.97        14

    accuracy                      

# 7. Conclusão
Comparamos vários modelos de classificação e observamos suas performances no conjunto de dados de vinhos. Cada modelo tem suas vantagens e pode ser mais adequado dependendo do contexto.



# 8. Exercícios
Agora é a sua vez! Realize as seguintes atividades e observe os resultados:

1. Altere o tamanho do conjunto de teste: Modifique o parâmetro test_size para 0.2 na função train_test_split e reavalie os modelos. Como isso afeta a acurácia?

2. Experimente diferentes valores de k no KNN: Altere o valor de n_neighbors para 3 e 7 no modelo KNN. Qual valor produz a melhor acurácia?

3. Remova a normalização dos dados: Comente ou remova as linhas onde aplicamos o StandardScaler e treine os modelos novamente. Quais modelos são mais afetados?

4. Ajuste a profundidade máxima da Árvore de Decisão: Defina o parâmetro max_depth=3 no DecisionTreeClassifier. Isso melhora ou piora o desempenho?

5. Use um kernel diferente no SVM: Altere o parâmetro kernel para 'linear' no modelo SVM. Compare os resultados com o kernel padrão.